# Generated by osate-cli/packaging/scripts/generate-homebrew-formula.sh.
class OsateCli < Formula
  desc "OSATE command-line interface for AADL workspaces"
  homepage "https://github.com/osate/aadl-tooling"
  license "LicenseRef-BSD-SEI"
  version "0.2.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/osate/aadl-tooling/releases/download/osate-cli-v0.2.1/osate-cli-0.2.1-macos-arm64.tar.gz"
      sha256 "1e2cef22d5b9a7eec5548ffd934f04c71bc5a9a9a2e73b463ed8dad16090d58f"
    else
      url "https://github.com/osate/aadl-tooling/releases/download/osate-cli-v0.2.1/osate-cli-0.2.1-macos-x64.tar.gz"
      sha256 "10ec3da75610130de1d051b5106708b5f087c460f9a55505fb963fdfae21e0e7"
    end
  end

  def install
    libexec.install Dir["*"]
    bin.write_exec_script libexec/"bin/osate-cli"
  end

  test do
    assert_match "usage:", shell_output("#{bin}/osate-cli --help")
  end
end
