# Generated by osate-cli/packaging/scripts/generate-homebrew-formula.sh.
class OsateCli < Formula
  desc "OSATE command-line interface for AADL workspaces"
  homepage "https://github.com/osate/aadl-tooling"
  license "LicenseRef-BSD-SEI"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/osate/aadl-tooling/releases/download/osate-cli-v0.2.0/osate-cli-0.2.0-macos-arm64.tar.gz"
      sha256 "55e7dcb1a271416e0911bf8b35af524c7a1efda8831ea9cdaa5ef96f923c07b9"
    else
      url "https://github.com/osate/aadl-tooling/releases/download/osate-cli-v0.2.0/osate-cli-0.2.0-macos-x64.tar.gz"
      sha256 "781039f58f272d1433949c7f6de66e0eb134a4530b746b5ef25bb7d524b84a02"
    end
  end

  def install
    libexec.install Dir["*"]
    bin.write_exec_script libexec/"bin/osate-cli"
  end

  test do
    assert_match "usage:", shell_output("#{bin}/osate-cli --help")
  end
end
