# Generated by osate-cli/packaging/scripts/generate-homebrew-formula.sh.
class OsateCli < Formula
  desc "OSATE command-line interface for AADL workspaces"
  homepage "https://github.com/osate/aadl-tooling"
  license "LicenseRef-BSD-SEI"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/osate/aadl-tooling/releases/download/osate-cli-v0.1.0/osate-cli-0.1.0-macos-arm64.tar.gz"
      sha256 "718c0ffda20444ed7ee7f887e3b5334a7b4b69815b3c0fecf43f64e8241d9241"
    else
      url "https://github.com/osate/aadl-tooling/releases/download/osate-cli-v0.1.0/osate-cli-0.1.0-macos-x64.tar.gz"
      sha256 "397fbb5095061690eb203b51689566e6725d43a7cd930f65efcb6271d0bccedd"
    end
  end

  def install
    libexec.install Dir["*"]
    bin.write_exec_script libexec/"bin/osate-cli"
  end

  test do
    assert_match "usage:", shell_output("#{bin}/osate-cli --help")
  end
end
